export const SIGN_UP_ERROR_MESSAGE = {
  noId: '아이디를 입력해주세요.',
  idRegex: '6-12자의 소문자 영문, 숫자만 사용 가능합니다.',
  idDuplicate: '중복된 아이디입니다.',
  passwordRegex: '반드시 영문, 숫자, 특수문자 중 2가지 이상 사용해 8자 이상',
  passwordLength: '비밀 번호는 8~20자 이내로 입력해야 합니다.',
  passwordCheck: '비밀번호가 일치하지 않습니다.',
  noNickname: '닉네임을 입력해주세요',
  nicknameDuplicate: '중복된 닉네임입니다.',
  noName: '이름을 입력하세요.',
  noBirth: '생년월일을 입력하세요.',
  noEmail: '이메일을 입력해주세요.',
  emailRegex: '올바른 이메일 형식이 아닙니다.',
  noCompanyName: '기업명을 입력하세요.',
  noPosition: '직책을 입력하세요',
};
