name: Merge To Ready
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize #PR에 커밋이 추가될 때 실행

jobs:
  update-status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write # 자동으로 이슈 상태 업데이트

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

      - name: Build Project
        run: npm run build
