name: Sync Fork With Upstream
on:
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    if: github.repository == 'BrainPix-front'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT_TOKEN}}
          ref: develop
          persition-credentials: false

      - name: Set up Git
        run: |
          git config user.name minejeong9919
          git config user.email "minjeong9919@github.com"

      - name: Add remote-url
        run: |
          git remote add forked-repo https://github.com/minjeong9919/BrainPix-front.git

      - name: Push changes to Forked-reop
        env:
          GITHUB_USERNAME: minjeong9919
          GITHUB_TOKEN: ${{secrets.PAT_TOKEN}}
        run: |
          git push -f http://$GITHUB_USERNAME:$GITHUB_TOKEN@https://github.com/minjeong9919/BrainPix-front.git develop

      - name: Clean up
        run: |
          git remote remove forked-repo
